/* ************************************
   TCSS 445 — Phase II (Part A: DDL)
   DBMS: Oracle LiveSQL
   Project: Husky Ride Share
   ************************************ */

/* Drop in dependency order (safe re-runs) */
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE Ratings CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE Matches CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE RideRequests CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE RideOffers CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE Vehicles CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE Users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; 
END;
/

/* ============ USERS ============ */
CREATE TABLE Users (
  user_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uw_email   VARCHAR2(120) NOT NULL UNIQUE,
  full_name  VARCHAR2(80)  NOT NULL,
  role       VARCHAR2(10)  DEFAULT 'rider'   NOT NULL
             CHECK (role IN ('rider','driver','both')),
  status     VARCHAR2(10)  DEFAULT 'ACTIVE'  NOT NULL
             CHECK (status IN ('ACTIVE','SUSPENDED')),
  created_at DATE          DEFAULT SYSDATE   NOT NULL
);

/* ============ VEHICLES ============ */
CREATE TABLE Vehicles (
  vehicle_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id  NUMBER,  -- nullable; if driver deleted we keep record but null the link
  make       VARCHAR2(40) NOT NULL,
  model      VARCHAR2(40) NOT NULL,
  color      VARCHAR2(20),
  plate      VARCHAR2(15) UNIQUE,
  capacity   NUMBER(2) DEFAULT 4 NOT NULL
             CHECK (capacity BETWEEN 1 AND 7),
  CONSTRAINT fk_vehicle_driver
    FOREIGN KEY (driver_id) REFERENCES Users(user_id) ON DELETE SET NULL
);

/* ============ RIDE OFFERS ============ */
CREATE TABLE RideOffers (
  offer_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id       NUMBER NOT NULL,
  vehicle_id      NUMBER,
  start_zone      VARCHAR2(40) NOT NULL,  -- e.g., 'Kent P&R'
  end_zone        VARCHAR2(40) NOT NULL,  -- e.g., 'UW Tacoma'
  start_time      DATE         NOT NULL,
  seats_available NUMBER(2)    DEFAULT 3 NOT NULL
                  CHECK (seats_available BETWEEN 0 AND 7),
  notes           VARCHAR2(200),
  CONSTRAINT fk_offer_driver
    FOREIGN KEY (driver_id)  REFERENCES Users(user_id)        ON DELETE CASCADE,
  CONSTRAINT fk_offer_vehicle
    FOREIGN KEY (vehicle_id) REFERENCES Vehicles(vehicle_id)  ON DELETE SET NULL
);

/* ============ RIDE REQUESTS ============ */
CREATE TABLE RideRequests (
  request_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rider_id      NUMBER      NOT NULL,
  from_zone     VARCHAR2(40) NOT NULL,
  to_zone       VARCHAR2(40) NOT NULL,
  desired_time  DATE         NOT NULL,
  seats_needed  NUMBER(2)    DEFAULT 1 NOT NULL
                CHECK (seats_needed BETWEEN 1 AND 4),
  status        VARCHAR2(12) DEFAULT 'open' NOT NULL
                CHECK (status IN ('open','matched','cancelled','completed')),
  CONSTRAINT fk_request_rider
    FOREIGN KEY (rider_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

/* ============ MATCHES (offer↔request) ============ */
CREATE TABLE Matches (
  match_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offer_id   NUMBER NOT NULL,
  request_id NUMBER NOT NULL,
  matched_at DATE   DEFAULT SYSDATE NOT NULL,
  status     VARCHAR2(12) DEFAULT 'pending' NOT NULL
             CHECK (status IN ('pending','confirmed','completed','cancelled')),
  CONSTRAINT uq_offer_request UNIQUE (offer_id, request_id),
  CONSTRAINT fk_match_offer
    FOREIGN KEY (offer_id)   REFERENCES RideOffers(offer_id)     ON DELETE CASCADE,
  CONSTRAINT fk_match_request
    FOREIGN KEY (request_id) REFERENCES RideRequests(request_id) ON DELETE CASCADE
);

/* ============ RATINGS ============ */
CREATE TABLE Ratings (
  rating_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rater_user_id  NUMBER NOT NULL,
  ratee_user_id  NUMBER NOT NULL,
  ride_date      DATE   NOT NULL,
  score          NUMBER(1) NOT NULL CHECK (score BETWEEN 1 AND 5),
  review_comment VARCHAR2(400),  -- Changed from 'comment' to avoid reserved word
  created_at     DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT fk_rating_rater
    FOREIGN KEY (rater_user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_rating_ratee
    FOREIGN KEY (ratee_user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
  CONSTRAINT chk_rater_ratee CHECK (rater_user_id <> ratee_user_id)
);

/* Helpful indexes */
CREATE INDEX ix_offer_start_time     ON RideOffers(start_time);
CREATE INDEX ix_request_desired_time ON RideRequests(desired_time);
CREATE INDEX ix_ratings_ratee        ON Ratings(ratee_user_id);

COMMIT;

/* ************************************ 
   PART B — SAMPLE DATA FOR HUSKY RIDESHARE (Oracle)
************************************ */

-- Insert Users data (using individual INSERT statements)
INSERT INTO Users (uw_email, full_name, role, status) VALUES ('eu.tellus@icloud.couk','Gwendolyn Wright','driver','ACTIVE');
INSERT INTO Users (uw_email, full_name, role, status) VALUES ('turpis.vitae.purus@icloud.couk','Quail Barton','driver','SUSPENDED');
INSERT INTO Users (uw_email, full_name, role, status) VALUES ('suspendisse.sagittis@icloud.org','Dolan Monroe','both','SUSPENDED');
INSERT INTO Users (uw_email, full_name, role, status) VALUES ('placerat.eget@icloud.org','Quinn Beard','both','ACTIVE');
INSERT INTO Users (uw_email, full_name, role, status) VALUES ('amet.nulla@protonmail.edu','Gail Savage','both','SUSPENDED');
INSERT INTO Users (uw_email, full_name, role, status) VALUES ('fusce.fermentum@hotmail.edu','Grant Hendricks','driver','SUSPENDED');
INSERT INTO Users (uw_email, full_name, role, status) VALUES ('tempus.scelerisque@aol.edu','Elvis Petty','rider','SUSPENDED');
INSERT INTO Users (uw_email, full_name, role, status) VALUES ('ipsum@protonmail.com','Mona Sosa','rider','ACTIVE');
INSERT INTO Users (uw_email, full_name, role, status) VALUES ('sagittis@hotmail.couk','Kaseem Fulton','driver','ACTIVE');
INSERT INTO Users (uw_email, full_name, role, status) VALUES ('donec.at.arcu@yahoo.couk','Harriet Fleming','driver','ACTIVE');

-- Insert Vehicles data
INSERT INTO Vehicles (driver_id, make, model, color, plate, capacity) VALUES (1,'Toyota','Prius','Blue','WA-PRU123',4);
INSERT INTO Vehicles (driver_id, make, model, color, plate, capacity) VALUES (10,'Honda','Civic','Silver','WA-CIV456',4);
INSERT INTO Vehicles (driver_id, make, model, color, plate, capacity) VALUES (9,'Subaru','Outback','Green','WA-OUT789',5);
INSERT INTO Vehicles (driver_id, make, model, color, plate, capacity) VALUES (4,'Tesla','Model 3','White','WA-EVX321',4);
INSERT INTO Vehicles (driver_id, make, model, color, plate, capacity) VALUES (6,'Ford','Escape','Black','WA-ESC654',4);
INSERT INTO Vehicles (driver_id, make, model, color, plate, capacity) VALUES (1,'Hyundai','Elantra','Red','WA-ELA852',4);
INSERT INTO Vehicles (driver_id, make, model, color, plate, capacity) VALUES (9,'Toyota','Camry','Gray','WA-CAM147',4);
INSERT INTO Vehicles (driver_id, make, model, color, plate, capacity) VALUES (4,'Kia','Niro','Blue','WA-NIR963',4);
INSERT INTO Vehicles (driver_id, make, model, color, plate, capacity) VALUES (10,'Chevrolet','Bolt','White','WA-BLT753',4);
INSERT INTO Vehicles (driver_id, make, model, color, plate, capacity) VALUES (1,'Honda','Accord','Black','WA-ACC159',5);

-- Insert RideOffers data
INSERT INTO RideOffers (driver_id, vehicle_id, start_zone, end_zone, start_time, seats_available, notes) 
VALUES (1, 1, 'Federal Way TC','UW Tacoma', TO_DATE('2025-11-10 07:30','YYYY-MM-DD HH24:MI'), 3,'Early run');

INSERT INTO RideOffers (driver_id, vehicle_id, start_zone, end_zone, start_time, seats_available, notes) 
VALUES (10, 2, 'Puyallup Station','UW Tacoma', TO_DATE('2025-11-10 08:00','YYYY-MM-DD HH24:MI'), 2,'Can detour 38th');

INSERT INTO RideOffers (driver_id, vehicle_id, start_zone, end_zone, start_time, seats_available, notes) 
VALUES (9, 3, 'Tacoma Dome','UW Tacoma', TO_DATE('2025-11-10 08:15','YYYY-MM-DD HH24:MI'), 3,'Near Dome');

INSERT INTO RideOffers (driver_id, vehicle_id, start_zone, end_zone, start_time, seats_available, notes) 
VALUES (4, 4, 'Downtown Seattle','UW Tacoma', TO_DATE('2025-11-10 07:00','YYYY-MM-DD HH24:MI'), 2,'Charging stop ok');

INSERT INTO RideOffers (driver_id, vehicle_id, start_zone, end_zone, start_time, seats_available, notes) 
VALUES (6, 5, 'Lakewood','UW Tacoma', TO_DATE('2025-11-11 09:00','YYYY-MM-DD HH24:MI'), 3,'Library drop');

INSERT INTO RideOffers (driver_id, vehicle_id, start_zone, end_zone, start_time, seats_available, notes) 
VALUES (1, 6, 'Kent P&R','UW Tacoma', TO_DATE('2025-11-11 07:40','YYYY-MM-DD HH24:MI'), 2,'No food pls');

INSERT INTO RideOffers (driver_id, vehicle_id, start_zone, end_zone, start_time, seats_available, notes) 
VALUES (9, 7, 'Auburn Station','UW Tacoma', TO_DATE('2025-11-11 07:10','YYYY-MM-DD HH24:MI'), 3,'Can play music');

INSERT INTO RideOffers (driver_id, vehicle_id, start_zone, end_zone, start_time, seats_available, notes) 
VALUES (4, 8, 'Gig Harbor P&R','UW Tacoma', TO_DATE('2025-11-12 08:05','YYYY-MM-DD HH24:MI'), 2,'Return 5pm');

INSERT INTO RideOffers (driver_id, vehicle_id, start_zone, end_zone, start_time, seats_available, notes) 
VALUES (10, 9, 'Federal Way TC','UW Tacoma', TO_DATE('2025-11-12 07:35','YYYY-MM-DD HH24:MI'), 2,'Pickup Lot A');

INSERT INTO RideOffers (driver_id, vehicle_id, start_zone, end_zone, start_time, seats_available, notes) 
VALUES (1, 10, 'Fife','UW Tacoma', TO_DATE('2025-11-12 08:00','YYYY-MM-DD HH24:MI'), 3,'Flexible by 10 min');

-- Insert RideRequests data
INSERT INTO RideRequests (rider_id, from_zone, to_zone, desired_time, seats_needed, status) 
VALUES (8, 'Federal Way TC','UW Tacoma', TO_DATE('2025-11-10 07:50','YYYY-MM-DD HH24:MI'), 1,'open');

INSERT INTO RideRequests (rider_id, from_zone, to_zone, desired_time, seats_needed, status) 
VALUES (5, 'Puyallup Station','UW Tacoma', TO_DATE('2025-11-10 08:10','YYYY-MM-DD HH24:MI'), 2,'open');

INSERT INTO RideRequests (rider_id, from_zone, to_zone, desired_time, seats_needed, status) 
VALUES (7, 'Tacoma Dome','UW Tacoma', TO_DATE('2025-11-10 08:25','YYYY-MM-DD HH24:MI'), 1,'open');

INSERT INTO RideRequests (rider_id, from_zone, to_zone, desired_time, seats_needed, status) 
VALUES (9, 'Fife','UW Tacoma', TO_DATE('2025-11-12 07:55','YYYY-MM-DD HH24:MI'),1,'open');

INSERT INTO RideRequests (rider_id, from_zone, to_zone, desired_time, seats_needed, status) 
VALUES (4, 'Gig Harbor P&R','UW Tacoma', TO_DATE('2025-11-12 08:00','YYYY-MM-DD HH24:MI'),1,'open');

INSERT INTO RideRequests (rider_id, from_zone, to_zone, desired_time, seats_needed, status) 
VALUES (1, 'Kent P&R','UW Tacoma', TO_DATE('2025-11-11 07:45','YYYY-MM-DD HH24:MI'), 2,'open');

INSERT INTO RideRequests (rider_id, from_zone, to_zone, desired_time, seats_needed, status) 
VALUES (6, 'Lakewood','UW Tacoma', TO_DATE('2025-11-11 09:10','YYYY-MM-DD HH24:MI'), 1,'open');

INSERT INTO RideRequests (rider_id, from_zone, to_zone, desired_time, seats_needed, status) 
VALUES (2, 'Auburn Station','UW Tacoma', TO_DATE('2025-11-11 07:20','YYYY-MM-DD HH24:MI'), 1,'open');

INSERT INTO RideRequests (rider_id, from_zone, to_zone, desired_time, seats_needed, status) 
VALUES (3, 'Downtown Seattle','UW Tacoma', TO_DATE('2025-11-10 06:55','YYYY-MM-DD HH24:MI'),1,'open');

INSERT INTO RideRequests (rider_id, from_zone, to_zone, desired_time, seats_needed, status) 
VALUES (10, 'Federal Way TC','UW Tacoma', TO_DATE('2025-11-12 07:40','YYYY-MM-DD HH24:MI'), 1,'open');

/* ========== MATCHES (10) ========== */
-- Clear any existing matches first
DELETE FROM Matches;

-- Insert Matches using only IDs that we know exist (1-10 for both offers and requests)
INSERT INTO Matches (offer_id, request_id, status) VALUES (1, 1, 'confirmed');
INSERT INTO Matches (offer_id, request_id, status) VALUES (2, 2, 'confirmed');
INSERT INTO Matches (offer_id, request_id, status) VALUES (3, 3, 'confirmed');
INSERT INTO Matches (offer_id, request_id, status) VALUES (4, 4, 'confirmed');
INSERT INTO Matches (offer_id, request_id, status) VALUES (5, 5, 'pending');
INSERT INTO Matches (offer_id, request_id, status) VALUES (6, 6, 'confirmed');
INSERT INTO Matches (offer_id, request_id, status) VALUES (7, 7, 'confirmed');
INSERT INTO Matches (offer_id, request_id, status) VALUES (8, 8, 'pending');
INSERT INTO Matches (offer_id, request_id, status) VALUES (1, 2, 'confirmed');
INSERT INTO Matches (offer_id, request_id, status) VALUES (2, 1, 'pending');

-- Insert Ratings data (using review_comment instead of comment)
INSERT INTO Ratings (rater_user_id, ratee_user_id, ride_date, score, review_comment) 
VALUES (10, 1, DATE '2025-11-10', 5,'On time, smooth');

INSERT INTO Ratings (rater_user_id, ratee_user_id, ride_date, score, review_comment) 
VALUES (5, 10, DATE '2025-11-10', 5,'Friendly driver');

INSERT INTO Ratings (rater_user_id, ratee_user_id, ride_date, score, review_comment) 
VALUES (8, 9, DATE '2025-11-10', 4,'Traffic but okay');

INSERT INTO Ratings (rater_user_id, ratee_user_id, ride_date, score, review_comment) 
VALUES (3, 4, DATE '2025-11-10', 5,'Great convo');

INSERT INTO Ratings (rater_user_id, ratee_user_id, ride_date, score, review_comment) 
VALUES (9, 6, DATE '2025-11-11', 5,'Clean car');

INSERT INTO Ratings (rater_user_id, ratee_user_id, ride_date, score, review_comment) 
VALUES (1, 6, DATE '2025-11-11', 4,'Left a bit early');

INSERT INTO Ratings (rater_user_id, ratee_user_id, ride_date, score, review_comment) 
VALUES (5, 9, DATE '2025-11-11', 5,'Music was nice');

INSERT INTO Ratings (rater_user_id, ratee_user_id, ride_date, score, review_comment) 
VALUES (8, 4, DATE '2025-11-12', 5,'Quick trip');

INSERT INTO Ratings (rater_user_id, ratee_user_id, ride_date, score, review_comment) 
VALUES (4, 10, DATE '2025-11-12', 4,'Parking was crowded');

INSERT INTO Ratings (rater_user_id, ratee_user_id, ride_date, score, review_comment) 
VALUES (10, 1, DATE '2025-11-12', 5,'Would ride again');

COMMIT;

/* ****************************************************
   PART C — Designing SQL Queries
   **************************************************** */

/* SQL Query 1 — 3+ table join
 Purpose: Show each confirmed ride with driver & rider names, start/end zones, and start time.
 Expected: One row per confirmed match; columns: driver, rider, zones, time, status.
*/
SELECT d.full_name AS driver_name,
       r.full_name AS rider_name,
       o.start_zone,
       o.end_zone,
       o.start_time,
       m.status
FROM Matches m
JOIN RideOffers   o ON m.offer_id   = o.offer_id
JOIN RideRequests q ON m.request_id = q.request_id
JOIN Users d ON o.driver_id = d.user_id
JOIN Users r ON q.rider_id  = r.user_id
WHERE m.status = 'confirmed'
ORDER BY o.start_time;

/* SQL Query 2 — Nested + GROUP BY (top-rated drivers via ALL)
 Purpose: Find driver(s) whose avg rating is ≥ every other driver's avg rating.
 Expected: 1+ rows (ties possible): driver, avg_score.
*/
SELECT u.full_name AS driver_name, AVG(t.score) AS avg_score
FROM Ratings t
JOIN Users   u ON t.ratee_user_id = u.user_id
WHERE u.role IN ('driver','both')
GROUP BY u.user_id, u.full_name
HAVING AVG(t.score) >= ALL (
  SELECT AVG(t2.score)
  FROM Ratings t2
  JOIN Users u2 ON t2.ratee_user_id = u2.user_id
  WHERE u2.role IN ('driver','both')
  GROUP BY u2.user_id
);

/* SQL Query 3 — Correlated subquery 
 Purpose: List offers where matched seats (pending/confirmed) exceed seats_available.
 Expected: 0+ rows: offer_id, driver, seats_available, seats_matched.
*/
SELECT o.offer_id,
       u.full_name AS driver_name,
       o.seats_available,
       (SELECT COUNT(*)
          FROM Matches m
         WHERE m.offer_id = o.offer_id
           AND m.status IN ('pending','confirmed')) AS seats_matched
FROM RideOffers o
JOIN Users u ON o.driver_id = u.user_id
WHERE o.seats_available < (
  SELECT COUNT(*) FROM Matches m
  WHERE m.offer_id = o.offer_id
    AND m.status IN ('pending','confirmed')
);

/* SQL Query 4 — FULL OUTER JOIN (supply vs demand by zone/time)
 Purpose: Compare offers and requests on same date/zone (who's unmatched?).
 Expected: Rows for matched or unmatched items; NULLs indicate no counterpart.
*/
SELECT COALESCE(o.start_zone, q.from_zone) AS zone,
       TRUNC(COALESCE(o.start_time, q.desired_time)) AS ride_day,
       o.offer_id,
       q.request_id
FROM RideOffers o
FULL OUTER JOIN RideRequests q
  ON o.start_zone  = q.from_zone
 AND o.end_zone    = q.to_zone
 AND TRUNC(o.start_time) = TRUNC(q.desired_time)
ORDER BY ride_day, zone;

/* SQL Query 5 — Set operation (people who both offered and requested rides)
 Purpose: Show users who are drivers at least once and also made a request.
 Expected: 0+ rows: user_id, name, email.
*/
SELECT u.user_id, u.full_name, u.uw_email
FROM Users u
WHERE u.user_id IN (
  SELECT driver_id FROM RideOffers
  INTERSECT
  SELECT rider_id FROM RideRequests
);

/* SQL Query 6 — Zone stats (aggregation + HAVING)
 Purpose: Avg seats offered per start_zone for 2025-11-10 to 2025-11-12, zones with ≥2 offers.
 Expected: zone, offers_count, avg_seats.
*/
SELECT o.start_zone,
       COUNT(*) AS offers_count,
       ROUND(AVG(o.seats_available), 2) AS avg_seats
FROM RideOffers o
WHERE TRUNC(o.start_time) BETWEEN DATE '2025-11-10' AND DATE '2025-11-12'
GROUP BY o.start_zone
HAVING COUNT(*) >= 2
ORDER BY offers_count DESC, start_zone;

/* SQL Query 7 — Driver utilization (matches vs capacity)
 Purpose: For each driver, show confirmed riders carried and seats offered across their offers.
 Expected: driver, confirmed_riders, seats_offered, utilization%.
*/
SELECT u.full_name AS driver_name,
       COUNT(CASE WHEN m.status = 'confirmed' THEN 1 END) AS confirmed_riders,
       SUM(o.seats_available) AS seats_offered,
       CASE
         WHEN SUM(o.seats_available) = 0 THEN 0
         ELSE ROUND(
           100 * COUNT(CASE WHEN m.status = 'confirmed' THEN 1 END) 
               / SUM(o.seats_available), 1)
       END AS utilization_pct
FROM Users u
JOIN RideOffers o ON o.driver_id = u.user_id
LEFT JOIN Matches m ON m.offer_id = o.offer_id
GROUP BY u.user_id, u.full_name
ORDER BY utilization_pct DESC, driver_name;

/* SQL Query 8 — Suspended users with activity (UNION + filter)
 Purpose: List SUSPENDED users who still appear as a driver in any offer or as a rider in any request.
 Expected: user, role, where_seen.
*/
SELECT DISTINCT u.full_name, u.status, 'driver_in_offers' AS where_seen
FROM Users u
JOIN RideOffers o ON o.driver_id = u.user_id
WHERE u.status = 'SUSPENDED'
UNION
SELECT DISTINCT u.full_name, u.status, 'rider_in_requests' AS where_seen
FROM Users u
JOIN RideRequests q ON q.rider_id = u.user_id
WHERE u.status = 'SUSPENDED';

/* SQL Query 9 — Drivers with offers on 2025-11-10 + their avg rating (3 tables)
 Purpose: For drivers who had an offer on Nov 10, show their average rating (if any).
 Expected: driver, offers_on_day, avg_score (nullable).
*/
SELECT u.full_name AS driver_name,
       COUNT(*) AS offers_on_2025_11_10,
       ROUND(AVG(t.score), 2) AS avg_rating
FROM Users u
JOIN RideOffers o ON o.driver_id = u.user_id
LEFT JOIN Ratings  t ON t.ratee_user_id = u.user_id
WHERE TRUNC(o.start_time) = DATE '2025-11-10'
GROUP BY u.user_id, u.full_name
ORDER BY offers_on_2025_11_10 DESC, NVL(AVG(t.score), 0) DESC;

/* SQL Query 10 — "Did the rider rate that driver?" (3 tables + aliasing)
 Purpose: Find rider/driver pairs where the rider later rated that driver for that ride day.
 Expected: rider, driver, ride_day, rating, comment.
*/
SELECT rusr.full_name AS rider_name,
       dusr.full_name AS driver_name,
       TRUNC(o.start_time) AS ride_day,
       t.score,
       t.review_comment  -- Changed from comment to review_comment
FROM Matches m
JOIN RideOffers   o    ON m.offer_id   = o.offer_id
JOIN RideRequests q    ON m.request_id = q.request_id
JOIN Users dusr        ON o.driver_id  = dusr.user_id
JOIN Users rusr        ON q.rider_id   = rusr.user_id
JOIN Ratings t         ON t.rater_user_id = rusr.user_id
                       AND t.ratee_user_id = dusr.user_id
                       AND t.ride_date = TRUNC(o.start_time)
WHERE m.status IN ('confirmed','completed')
ORDER BY ride_day, driver_name, rider_name;